"""Define LLM chains"""
from langchain import LLMChain

from config.models import (
    SCENARIO_GENERATION_MODEL,
    SEED_INSTANCE_GENERATION_MODEL,
    INSTRUCTION_FINETUNING_GENERATION_MODEL,
)
from config.prompts import (
    SCENARIO_GENERATION_PROMPT,
    SEED_INSTANCE_GENERATION_PROMPT,
    INSTRUCTION_FINETUNING_GENERATION_PROMPT,
)

SCENARIO_GENERATION_CHAIN = LLMChain(
    llm=SCENARIO_GENERATION_MODEL, prompt=SCENARIO_GENERATION_PROMPT
)

SEED_INSTANCE_GENERATION_CHAIN = LLMChain(
    llm=SEED_INSTANCE_GENERATION_MODEL, prompt=SEED_INSTANCE_GENERATION_PROMPT
)

INSTRUCTION_FINETUNING_GENERATION_CHAIN = LLMChain(
    llm=INSTRUCTION_FINETUNING_GENERATION_MODEL,
    prompt=INSTRUCTION_FINETUNING_GENERATION_PROMPT,
)
